### PR TITLE
fix: reset biometry on pin change

### LINKED ISSUE #170: Biometry issue with resetting pin
During the execution of the app if the pin is changed we cannot send transactions using biometry until the app is closed and opened again.

This behavior can be reproduced by:
1. Open the wallet
1. Change the pin
1. Enable biometry (tested with fingerprint on an Android)
1. Try to send a transaction, it will fail

The error itself seems to change if the biometry was enabled when the pin is changed but if will fail when trying to send the transaction to the mining service either way.

After reproducing the error you can close then open the wallet and if biometry was enabled it will ask for biometry and pin to start.

### PR DESCRIPTION
**Pull request by r4mmer**
### Acceptance Criteria
- Change the Keychain password when changing the pin

This closes #170 

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

### CODE REVIEW

**Review by andreabadesso — APPROVED** [review]

File: src/utils.js [hunk 1]
```diff
@@ -365,11 +366,18 @@ export const guessPin = async (accessData, progressCb) => {
...
+  const success = hathorLib.wallet.changePinAndPassword({
     oldPin,
     newPin,
     oldPassword: oldPin,
     newPassword: newPin,
-  })
-);
+  });
+  if (success) {
+    Keychain.setGenericPassword(KEYCHAIN_USER, newPin, {
```
Comment (pedroferreira1) [inline src/utils.js:377]: I feel we should create an util method in this same file `setKeychainPassword(pin)` that does this code, so we don't repeat this here and in the `startWallet` method. What do you think?

File: src/utils.js [hunk 2]
```diff
@@ -359,17 +360,32 @@ export const guessPin = async (accessData, progressCb) => {
   });
 };
 
+/**
+ * Set the pin on the keychain so the user can use biometry
+ * @params {string} pinin
```
Comment (pedroferreira1) [inline src/utils.js:365]: Typo pin

**Review by pedroferreira1 — APPROVED** [review]

File: src/utils.js (hunk 2 above)
Comment (r4mmer) [reply src/utils.js]: Fixed
