### PR TITLE
fix: White bar below custom network

### LINKED ISSUE #668: Remove white space below "Custom Network" header
Remove the unnecessary white space below the "Custom Network" header, that was added in #642.

https://github.com/HathorNetwork/hathor-wallet-mobile/blob/491d094ca6dae277d21a7fde6329a88dace25ac5/src/screens/Dashboard.js#L194

See below for a visual reference
Sample white space

### PR DESCRIPTION
**Pull request by tuliomir**
### Acceptance Criteria
- Resolves #668 

### Visualization
Replaces white with gray

### Security Checklist
- [X] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

### Alternatives
We could also remove the spacing entirely, but it wouldn't feel correct. See below
668 before after

### CODE REVIEW

File: src/screens/Dashboard.js [hunk 1]
```diff
@@ -191,7 +191,6 @@ const TokensHeader = () => (
 const styles = StyleSheet.create({
   wrapper: {
     flex: 1,
-    marginTop: 8,
```
Comment (andreabadesso) [inline src/screens/Dashboard.js:194]: Should we keep the margin, but paint the background with the same grey color as the rest?

Comment (tuliomir) [reply src/screens/Dashboard.js:194]: Implemented this on [c7eabdb](https://github.com/HathorNetwork/hathor-wallet-mobile/pull/674/commits/c7eabdbe35cb9cdb78829299f0e7f35eb07c63fb). Indeed it looks better.

**Review by pedroferreira1 — APPROVED** [review]

**Review by obiyankenobi — APPROVED** [review]
